import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowRight, MapPin, PackageCheck, UserRound, Weight } from 'lucide-react';
import { api } from '../lib/api.js';
import { useAuth } from '../context/auth-context.jsx';
import { ErrorState, Loading, PageHeader, StatusBadge, labelStatus } from '../components/ui.jsx';

const nextDriverStatus={assigned:'accepted',accepted:'picked_up',picked_up:'in_transit'};
export default function DeliveryDetailPage(){const{id}=useParams();const navigate=useNavigate();const{user}=useAuth();const[d,setD]=useState(null);const[error,setError]=useState('');const[busy,setBusy]=useState(false);const load=()=>api.get(`/deliveries/${id}`).then(r=>setD(r.data.data)).catch(e=>setError(e.response?.data?.error?.message??'Could not load delivery.'));useEffect(load,[id]);const transition=async(status)=>{if(!confirm(`Move this delivery to ${labelStatus(status)}?`))return;setBusy(true);try{const{data}=await api.patch(`/deliveries/${id}/status`,{status});setD(data.data);}catch(e){setError(e.response?.data?.error?.message??'Status change failed.');}finally{setBusy(false);}};
if(error)return <ErrorState message={error} retry={load}/>;if(!d)return <Loading/>;const next=user.role==='driver'?nextDriverStatus[d.status]:null;return <><PageHeader title={d.trackingNumber} description={`${d.priority} priority · Created ${new Intl.DateTimeFormat('en-IN',{dateStyle:'medium'}).format(new Date(d.createdAt))}`} action={<div className="header-actions"><StatusBadge status={d.status}/>{next&&<button disabled={busy} className="button" onClick={()=>transition(next)}>Mark {labelStatus(next)} <ArrowRight/></button>}</div>}/>
<section className="detail-grid"><div className="route-board"><div><MapPin/><span>Pickup</span><strong>{d.pickupAddress.line1}</strong><small>{d.pickupAddress.city}, {d.pickupAddress.state} {d.pickupAddress.postalCode}</small></div><div className="route-line"><i/><b>{labelStatus(d.status)}</b><i/></div><div><MapPin/><span>Destination</span><strong>{d.deliveryAddress.line1}</strong><small>{d.deliveryAddress.city}, {d.deliveryAddress.state} {d.deliveryAddress.postalCode}</small></div></div><aside className="detail-facts"><h2>Shipment facts</h2><dl><div><dt><Weight/>Weight</dt><dd>{d.packageWeightKg} kg</dd></div><div><dt><PackageCheck/>Contents</dt><dd>{d.packageDescription}</dd></div><div><dt><UserRound/>Customer</dt><dd>{d.customer.name}</dd></div><div><dt>Expected</dt><dd>{new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(d.expectedDeliveryAt))}</dd></div></dl></aside></section>
<section className="timeline"><h2>Delivery timeline</h2>{[...d.history].reverse().map((h,i)=><div className="timeline-event" key={`${h.at}-${i}`}><i/><div><strong>{labelStatus(h.status)}</strong><p>{h.note||'Status updated'}</p><time>{new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(h.at))}</time></div></div>)}</section><button className="text-button" onClick={()=>navigate('/deliveries')}>← Back to manifest</button></>}
