import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowRight } from 'lucide-react';
import { api } from '../lib/api.js';
import { PageHeader } from '../components/ui.jsx';

const emptyAddress={line1:'',city:'',state:'',postalCode:''};
export default function NewDeliveryPage(){const navigate=useNavigate();const [form,setForm]=useState({pickupAddress:{...emptyAddress},deliveryAddress:{...emptyAddress},packageDescription:'',packageWeightKg:'',priority:'standard',expectedDeliveryAt:''});const[error,setError]=useState('');const[busy,setBusy]=useState(false);const address=(key,field,value)=>setForm({...form,[key]:{...form[key],[field]:value}});const submit=async(e)=>{e.preventDefault();setBusy(true);setError('');try{const{data}=await api.post('/deliveries',form);navigate(`/deliveries/${data.data._id}`);}catch(err){setError(err.response?.data?.error?.message??'Could not create delivery.');}finally{setBusy(false);}};
return <><PageHeader title="Request a delivery" description="Provide the route, package and expected delivery window."/><form className="delivery-form" onSubmit={submit}><fieldset><legend>Pickup</legend>{[['line1','Street address'],['city','City'],['state','State'],['postalCode','Postal code']].map(([f,l])=><label key={f}>{l}<input required value={form.pickupAddress[f]} onChange={e=>address('pickupAddress',f,e.target.value)}/></label>)}</fieldset><fieldset><legend>Destination</legend>{[['line1','Street address'],['city','City'],['state','State'],['postalCode','Postal code']].map(([f,l])=><label key={f}>{l}<input required value={form.deliveryAddress[f]} onChange={e=>address('deliveryAddress',f,e.target.value)}/></label>)}</fieldset><fieldset className="package-fields"><legend>Package</legend><label>Description<textarea required minLength="3" value={form.packageDescription} onChange={e=>setForm({...form,packageDescription:e.target.value})}/></label><label>Weight (kg)<input required min="0.1" step="0.1" type="number" value={form.packageWeightKg} onChange={e=>setForm({...form,packageWeightKg:e.target.value})}/></label><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>standard</option><option>express</option><option>urgent</option></select></label><label>Expected by<input required type="datetime-local" value={form.expectedDeliveryAt} onChange={e=>setForm({...form,expectedDeliveryAt:e.target.value})}/></label></fieldset>{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="button button--secondary" onClick={()=>navigate(-1)}>Cancel</button><button className="button" disabled={busy}>{busy?'Creating…':'Create request'} <ArrowRight/></button></div></form></>}
