import request from 'supertest';
import { beforeEach, describe, expect, it } from 'vitest';
import { createApp } from '../app.js';
import { User } from '../models/user.js';
import { Delivery } from '../models/delivery.js';
import { Driver } from '../models/driver.js';
import { Vehicle } from '../models/vehicle.js';
import bcrypt from 'bcryptjs';

const app=createApp();let customer;let other;let tokens={};const address={line1:'1 Test Street',city:'Pune',state:'Maharashtra',postalCode:'411001'};
beforeEach(async()=>{for(const [role,email] of [['customer','c@example.com'],['other','o@example.com'],['driver','d@example.com'],['manager','m@example.com']]){const actualRole=role==='other'?'customer':role;const user=await User.create({name:role,email,role:actualRole,passwordHash:await User.hashPassword('Password1')});if(role==='customer')customer=user;if(role==='other')other=user;const login=await request(app).post('/api/v1/auth/login').send({email,password:'Password1'});tokens[role]=login.body.data.accessToken;}});
const makeDelivery=()=>Delivery.create({trackingNumber:`FF-${Date.now()}-${Math.random()}`,customer:customer._id,pickupAddress:address,deliveryAddress:address,packageDescription:'Test package',packageWeightKg:5,expectedDeliveryAt:new Date(Date.now()+86400000),history:[{status:'pending',actor:customer._id}]});
describe('delivery authorization and lifecycle',()=>{
  it('isolates one customer from another customer delivery',async()=>{const delivery=await makeDelivery();await request(app).get(`/api/v1/deliveries/${delivery._id}`).set('Authorization',`Bearer ${tokens.other}`).expect(403);});
  it('filters list results by the signed-in customer',async()=>{await makeDelivery();await Delivery.create({trackingNumber:'FF-OTHER',customer:other._id,pickupAddress:address,deliveryAddress:address,packageDescription:'Other parcel',packageWeightKg:2,expectedDeliveryAt:new Date(Date.now()+86400000),history:[{status:'pending',actor:other._id}]});const response=await request(app).get('/api/v1/deliveries?limit=10').set('Authorization',`Bearer ${tokens.customer}`).expect(200);expect(response.body.data).toHaveLength(1);});
  it('rejects an invalid pending to delivered transition',async()=>{const delivery=await makeDelivery();const response=await request(app).patch(`/api/v1/deliveries/${delivery._id}/status`).set('Authorization',`Bearer ${tokens.manager}`).send({status:'delivered'}).expect(409);expect(response.body.error.code).toBe('INVALID_STATUS_TRANSITION');});
  it('hashes and enforces the OTP for customer-created deliveries',async()=>{const created=await request(app).post('/api/v1/deliveries').set('Authorization',`Bearer ${tokens.customer}`).send({pickupAddress:address,deliveryAddress:address,packageDescription:'OTP protected package',packageWeightKg:5,expectedDeliveryAt:new Date(Date.now()+86400000),deliveryOtp:'1357'}).expect(201);expect(created.body.data.proof?.otpHash).toBeUndefined();const delivery=await Delivery.findById(created.body.data._id).select('+proof.otpHash');expect(await bcrypt.compare('1357',delivery.proof.otpHash)).toBe(true);const driverUser=await User.findOne({email:'d@example.com'});const profile=await Driver.create({user:driverUser._id,licenseNumber:'OTP-LICENSE',licenseExpiresAt:new Date(Date.now()+86400000),status:'busy',currentDelivery:delivery._id});delivery.status='in_transit';delivery.assignedDriver=profile._id;await delivery.save();await request(app).post(`/api/v1/deliveries/${delivery._id}/proof`).set('Authorization',`Bearer ${tokens.driver}`).send({recipientName:'Recipient',otp:'9999'}).expect(422);await request(app).post(`/api/v1/deliveries/${delivery._id}/proof`).set('Authorization',`Bearer ${tokens.driver}`).send({recipientName:'Recipient',otp:'1357'}).expect(200);});
  it('rejects proof when a legacy delivery has no configured OTP',async()=>{const driverUser=await User.findOne({email:'d@example.com'});const delivery=await makeDelivery();const profile=await Driver.create({user:driverUser._id,licenseNumber:'LEGACY-LICENSE',licenseExpiresAt:new Date(Date.now()+86400000),status:'busy',currentDelivery:delivery._id});delivery.status='in_transit';delivery.assignedDriver=profile._id;await delivery.save();const response=await request(app).post(`/api/v1/deliveries/${delivery._id}/proof`).set('Authorization',`Bearer ${tokens.driver}`).send({recipientName:'Recipient',otp:'1357'}).expect(409);expect(response.body.error.code).toBe('DELIVERY_OTP_NOT_CONFIGURED');});
  it('prevents concurrent assignment of one driver and vehicle',async()=>{const driverUser=await User.findOne({email:'d@example.com'});const profile=await Driver.create({user:driverUser._id,licenseNumber:'TEST-LICENSE',licenseExpiresAt:new Date(Date.now()+86400000),status:'available'});const vehicle=await Vehicle.create({registrationNumber:'TEST-VAN',type:'van',capacityKg:100,status:'available'});const first=await makeDelivery();const second=await makeDelivery();const responses=await Promise.all([first,second].map(delivery=>request(app).post(`/api/v1/deliveries/${delivery._id}/assign`).set('Authorization',`Bearer ${tokens.manager}`).send({driverId:profile._id.toString(),vehicleId:vehicle._id.toString()})));expect(responses.map(r=>r.status).sort()).toEqual([200,409]);expect(await Delivery.countDocuments({assignedDriver:profile._id})).toBe(1);});
  it('accepts proof only from the assigned driver and releases resources',async()=>{const driverUser=await User.findOne({email:'d@example.com'});const delivery=await makeDelivery();const profile=await Driver.create({user:driverUser._id,licenseNumber:'PROOF-LICENSE',licenseExpiresAt:new Date(Date.now()+86400000),status:'busy',currentDelivery:delivery._id});const vehicle=await Vehicle.create({registrationNumber:'PROOF-VAN',type:'van',capacityKg:100,status:'in_use',currentDelivery:delivery._id});delivery.status='in_transit';delivery.assignedDriver=profile._id;delivery.assignedVehicle=vehicle._id;delivery.proof={otpHash:await bcrypt.hash('2468',4)};await delivery.save();await request(app).post(`/api/v1/deliveries/${delivery._id}/proof`).set('Authorization',`Bearer ${tokens.driver}`).field('recipientName','Test Recipient').field('otp','2468').field('driverNotes','Package handed over').expect(200);expect((await Delivery.findById(delivery._id)).status).toBe('delivered');expect((await Driver.findById(profile._id)).status).toBe('available');});
  it('searches and paginates the operational manifest',async()=>{const match=await makeDelivery();match.packageDescription='Distinctive turbine component';await match.save();await makeDelivery();await Delivery.syncIndexes();const response=await request(app).get('/api/v1/deliveries?search=turbine&limit=1').set('Authorization',`Bearer ${tokens.manager}`).expect(200);expect(response.body.data).toHaveLength(1);expect(response.body.data[0].packageDescription).toContain('turbine');});
});
